### ISSUE TITLE
Plan the next PSA integration meeting on 2017-07-10.

### ISSUE THREAD

**Issue by mbredel** [sonata-nfv/son-security-pilot#38]
Please help to plan the next PSA integration meeting. That is, list the tasks (maybe linked to GitHub issues) below:

* Test the SNORT VM manually #23

**Comment by mbredel** [comment]
Question: Instead of collecting the ideas and tasks for the integration meeting in this issue, we can create another PSA sub-project and assign issues to that project. Thus, this issue here only links to the sub-project. This is not as convenient as really having sub-projects like in Jira - but may work. What do you think?

**Comment by Navdeepuniyal** [comment]
Integration meeting was done on 10 July.

NOTE: ‘pfsense’ seems to be tricky to deploy in an automated way but ‘ufw’ (Ubuntu’ native) and ‘firewalld’ (CentOS’ native) can be an alternative (and also has configurable files to handle)
